Add test's functions
muradrmagomedov/go-testify pull request #1
Opened 2024-04-10 22:36 UTC by muradrmagomedov

2024-04-10 23:02 UTC, dirtymew requested changes
Привет Мурад

нужно переделать - не совсем верно оформил код

2024-04-10 23:02 UTC, dirtymew commented on precode.go
> +func TestMainHandlerWhenOk(t *testing.T) {
тесты в go оформляются в отдельном файле названом *_test.go

2024-04-10 23:02 UTC, dirtymew commented on precode.go
> +func TestMainHandlerWhenOk(t *testing.T) {
тест должны запускаться командой go test

2024-04-10 23:02 UTC, dirtymew commented on precode.go
> +	assert.Equal(t, responseRecorder.Code, http.StatusOK)
тут require

2024-04-10 23:02 UTC, dirtymew commented on precode.go
> +	require.NotEmpty(t, responseRecorder.Body.String())
assert

2024-04-10 23:02 UTC, dirtymew commented on precode.go
> +	require.NotEmpty(t, responseRecorder.Body.String())
тут NotEmpty(t, responseRecorder.Body) - понятно почему?

2024-04-11 08:42 UTC, muradrmagomedov commented on precode.go
> +	require.NotEmpty(t, responseRecorder.Body.String())
> тут NotEmpty(t, responseRecorder.Body) - понятно почему?

Привет, предполагаю) но лучше поясни

2024-04-11 17:44 UTC, dirtymew approved these changes
Привет Мурад

Есть что улучшить но работа выполнена - зачет

2024-04-11 17:44 UTC, dirtymew commented on precode_test.go
> +	assert.Equal(t, responseRecorder.Code, http.StatusBadRequest)
тут require

2024-04-11 17:44 UTC, dirtymew commented on precode.go
> +	require.NotEmpty(t, responseRecorder.Body.String())
если посмотреть код то видно что если Body nil Body.String() вернет строку "<nil>" это не будет пустой строкой

2024-08-18 12:49 UTC, merged